imie_game_homepage:
    path:     /
    defaults: { _controller: ImieGameBundle:Home:index }

imie_game_login:
    path:   /login
    defaults: { _controller: ImieGameBundle:Home:login }

imie_game_logout:
    path:   /logout
    defaults: { _controller: ImieGameBundle:Home:logout }

imie_game_gamepage:
    path:     /game
    defaults: { _controller: ImieGameBundle:Game:index }

imie_game_changetheme:
    path:     /change-theme/{bgcolor}
    defaults: { _controller: ImieGameBundle:Theme:change }
