<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-07-18 16:09:04.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Imie\GameBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Imie\GameBundle\Entity\Game
 *
 * @ORM\Entity(repositoryClass="GameRepository")
 * @ORM\Table(name="game", indexes={@ORM\Index(name="FK_GAME_PLAYER_idx", columns={"id_player"}), @ORM\Index(name="FK_GAME_WORD_idx", columns={"id_word"})})
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $id_player;

    /**
     * @ORM\Column(type="integer")
     */
    protected $id_word;

    /**
     * @ORM\Column(name="`state`", type="string", length=12)
     */
    protected $state;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $started;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $ended;

    /**
     * @ORM\ManyToOne(targetEntity="Player", inversedBy="games")
     * @ORM\JoinColumn(name="id_player", referencedColumnName="id")
     */
    protected $player;

    /**
     * @ORM\ManyToOne(targetEntity="Word", inversedBy="games")
     * @ORM\JoinColumn(name="id_word", referencedColumnName="id")
     */
    protected $word;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of id_player.
     *
     * @param integer $id_player
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setIdPlayer($id_player)
    {
        $this->id_player = $id_player;

        return $this;
    }

    /**
     * Get the value of id_player.
     *
     * @return integer
     */
    public function getIdPlayer()
    {
        return $this->id_player;
    }

    /**
     * Set the value of id_word.
     *
     * @param integer $id_word
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setIdWord($id_word)
    {
        $this->id_word = $id_word;

        return $this;
    }

    /**
     * Get the value of id_word.
     *
     * @return integer
     */
    public function getIdWord()
    {
        return $this->id_word;
    }

    /**
     * Set the value of state.
     *
     * @param string $state
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setState($state)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Get the value of state.
     *
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Set the value of started.
     *
     * @param \DateTime $started
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setStarted($started)
    {
        $this->started = $started;

        return $this;
    }

    /**
     * Get the value of started.
     *
     * @return \DateTime
     */
    public function getStarted()
    {
        return $this->started;
    }

    /**
     * Set the value of ended.
     *
     * @param \DateTime $ended
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setEnded($ended)
    {
        $this->ended = $ended;

        return $this;
    }

    /**
     * Get the value of ended.
     *
     * @return \DateTime
     */
    public function getEnded()
    {
        return $this->ended;
    }

    /**
     * Set Player entity (many to one).
     *
     * @param \Imie\GameBundle\Entity\Player $player
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setPlayer(Player $player = null)
    {
        $this->player = $player;

        return $this;
    }

    /**
     * Get Player entity (many to one).
     *
     * @return \Imie\GameBundle\Entity\Player
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * Set Word entity (many to one).
     *
     * @param \Imie\GameBundle\Entity\Word $word
     * @return \Imie\GameBundle\Entity\Game
     */
    public function setWord(Word $word = null)
    {
        $this->word = $word;

        return $this;
    }

    /**
     * Get Word entity (many to one).
     *
     * @return \Imie\GameBundle\Entity\Word
     */
    public function getWord()
    {
        return $this->word;
    }

    public function __sleep()
    {
        return array('id', 'id_player', 'id_word', 'state', 'started', 'ended');
    }
}