<?php

namespace Imie\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function createIfNotExists($playerName) {
        $em = $this->getEntityManager();
        $dql = 'SELECT player.id FROM ImieGameBundle:Player player WHERE player.name = :name';
        $query = $em->createQuery($dql);
        $query->setParameter('name', $playerName);

        $res = $query->getResult();
        if(!empty($res)){
            return $res[0]['id'];
        }
        else{
            $player = new Player();
            $player->setName($playerName);
            $em->persist($player);
            $em->flush();
            return $player->getId();
        }
    }
}
