<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-07-18 16:09:05.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Imie\GameBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Imie\GameBundle\Entity\Theme
 *
 * @ORM\Entity(repositoryClass="ThemeRepository")
 * @ORM\Table(name="theme")
 */
class Theme
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=6)
     */
    protected $color_bg;

    /**
     * @ORM\OneToMany(targetEntity="PlayerTheme", mappedBy="theme")
     * @ORM\JoinColumn(name="id", referencedColumnName="id_theme")
     */
    protected $playerThemes;

    public function __construct()
    {
        $this->playerThemes = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Imie\GameBundle\Entity\Theme
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of color_bg.
     *
     * @param string $color_bg
     * @return \Imie\GameBundle\Entity\Theme
     */
    public function setColorBg($color_bg)
    {
        $this->color_bg = $color_bg;

        return $this;
    }

    /**
     * Get the value of color_bg.
     *
     * @return string
     */
    public function getColorBg()
    {
        return $this->color_bg;
    }

    /**
     * Add PlayerTheme entity to collection (one to many).
     *
     * @param \Imie\GameBundle\Entity\PlayerTheme $playerTheme
     * @return \Imie\GameBundle\Entity\Theme
     */
    public function addPlayerTheme(PlayerTheme $playerTheme)
    {
        $this->playerThemes[] = $playerTheme;

        return $this;
    }

    /**
     * Remove PlayerTheme entity from collection (one to many).
     *
     * @param \Imie\GameBundle\Entity\PlayerTheme $playerTheme
     * @return \Imie\GameBundle\Entity\Theme
     */
    public function removePlayerTheme(PlayerTheme $playerTheme)
    {
        $this->playerThemes->removeElement($playerTheme);

        return $this;
    }

    /**
     * Get PlayerTheme entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPlayerThemes()
    {
        return $this->playerThemes;
    }

    public function __sleep()
    {
        return array('id', 'color_text', 'color_bg');
    }
}